### ISSUE TITLE
Subscribe to event

### ISSUE THREAD

**Issue by joaopauloalbq** [doronbehar/lua-pulseaudio_cli#1]
Good morning Doron, I hope you're well and safe 🇮🇱

Is it possible to create a callback to notify us as soon as the audio server changes?

In _pactl_ there is a command called _subscribe_ for that.

As an Awesome WM user this is a very useful feature to update our sound widget when a headphone is connected or when other programs change the volume/sink.

**Comment by doronbehar** [comment]
Hello @joaopauloalbq . Thanks for your concerns. Currently there is no API for doing that for as far as I remember. I haven't touched this repo in a long time, and I don't use it anymore. So I leave to you the adventure to discover how to do that. I will turn this into an archived repository.
